language: node_js
node_js:
- '10'
branches:
  only:
  - master
  - "/^v[0-9](\\.[0-9]+)(\\.[0-9]+)?$/"
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run test
deploy:
  provider: npm
  email: ajainvivek07@gmail.com
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: ajainvivek/s3-kms
